# Sudoku: brute force algorithm

In [2]:
import numpy as np

## Exercise 01
Create an array out of a list of 5 float values. Replace the second element of an array with a logical `True` value. Think what the final array values will be before printing out the array.

In [3]:
an_array = np.array([1.0, 2.3, 4.0, 52.2, -3])
an_array[1] = True
print(an_array)

[ 1.   1.   4.  52.2 -3. ]


## Exercise 02
Create two arrays with 5 float values. Add `2` to each element of the first array and multiply arrays elementwise. Print out 2 and 3 elements of the final array using slicing.

In [49]:
array_1 = np.array([1.0, 2.3, 4.0, 52.2, -3])
array_2 = np.array([2.0, -5, -2.0, 0.1, -3])
result = (array_1 + 2) * array_2
print(result[1:3])

[-21.5 -12. ]


## Exercise 03
Create an array of a list of 5 float values. Compute and print mean and minimual values of the array.

In [54]:
an_array = np.array([1.0, 2.3, 4.0, 52.2, -3])
print(np.mean(an_array), np.min(an_array))

11.3 -3.0


## Exercise 04
Define a 4×4 list of lists with numbers going from 1 to 16. Extract and print second column, third row, lower right quadrant.

In [9]:
square_lists = [[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]]

# second column
[row[1] for row in square_lists]

# third row
square_lists[2]

# lower right 
lower_right = []
for row in square_lists[2:]:
    lower_right.append(row[2:])
lower_right

[[11, 12], [15, 16]]

Convert list of lists to a NumPy matrix and repeat exercise by via slicing.

In [6]:
square = np.array(square_lists)

# second column
print(square[:, 1])

# third row
print(square[2, :])

# lower right quadrant
print(square[2:, 2:])

[ 2  6 10 14]
[ 9 10 11 12]
[[11 12]
 [15 16]]


## Exercise 05
Using [numpy.ones()](https://numpy.org/doc/stable/reference/generated/numpy.ones.html) function, create a 4×4 matrix filled with `7`.

In [50]:
np.ones((4, 4)) + 6

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

## Exercise 06
Generate a 4×5 matrix filled with normally distributed random numbers with mean of 3 and standard deviation of 1.

In [2]:
np.random.normal(3, 1, (4, 5))

array([[ 4.34788363,  3.23102235,  1.7663542 ,  4.27731085,  4.43687909],
       [ 3.13138163,  3.71286465,  2.70225638,  2.51041789,  2.8575209 ],
       [ 4.57086305,  4.19195134,  4.52772209,  3.81097419,  2.4169515 ],
       [-0.19402309,  2.67891953,  3.02357861,  3.4221514 ,  2.26261788]])

## Exercise 07
Generate a sequence of number from 1 to 10 using arange.

In [3]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Do the same but using linspace.

In [4]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Exercise 08
Generate a 4×4 Sudoku matrix out of ordered rows (stacked vertically) or columns (stacked horizontally).

Ordered by row (stacked vertically)

In [6]:
a_row = np.arange(1, 5)
np.stack([a_row, a_row, a_row, a_row], axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

Ordered by column (stacked horizontally)

In [7]:
a_column = np.arange(1, 5)
np.stack([a_column, a_column, a_column, a_column], axis=1)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

## Exercise 09
Create a four-element row vector, i.e., its [shape](https://numpy.org/doc/stable/reference/generated/numpy.shape.html) must be `(1, 4)`. Stack it to create 

1. `(1, 16)` array
2. `(4, 4)` array
3. Use result of #1 and transpose it to get a `(16, 1)` array.

In [15]:
row_vector = np.array([[1, 2, 3, 4]])

#1
print(np.hstack([row_vector, row_vector, row_vector, row_vector]))

#2
print(np.vstack([row_vector, row_vector, row_vector, row_vector]))

#3
print(np.transpose(np.hstack([row_vector, row_vector, row_vector, row_vector])))

[[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1]
 [2]
 [3]
 [4]
 [1]
 [2]
 [3]
 [4]
 [1]
 [2]
 [3]
 [4]
 [1]
 [2]
 [3]
 [4]]


Create a four-element column vector, i.e., its [shape](https://numpy.org/doc/stable/reference/generated/numpy.shape.html) must be `(4, 1)`. Stack it to create 

1. `(16, 1)` array
2. `(4, 4)` array
3. Use result of #1 and transpose it to get a `(1, 16)` array.

In [17]:
col_vector = np.transpose(row_vector)

#1
print(np.vstack([col_vector, col_vector, col_vector, col_vector]))

#2
print(np.hstack([col_vector, col_vector, col_vector, col_vector]))

#3
print(np.transpose(np.vstack([col_vector, col_vector, col_vector, col_vector])))

[[1]
 [2]
 [3]
 [4]
 [1]
 [2]
 [3]
 [4]
 [1]
 [2]
 [3]
 [4]
 [1]
 [2]
 [3]
 [4]]
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
[[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]]


## Exercise 10
Generate a 4×4 matrix using [arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) and [repeat](https://numpy.org/doc/stable/reference/generated/numpy.repeat.html). Create a column vector for values 1 to 4 from an array generated by [arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) (check its shape, should be `(4, 1)`). Repeat that column vector four times to create a 4×4 matrix. Think and experiment with `axis` parameter of the [repeat](https://numpy.org/doc/stable/reference/generated/numpy.repeat.html) function. Your matrix should look like this:
| 1 | 1 | 1 | 1 |
|---|---|---|---|
| 2 | 2 | 2 | 2 |
| 3 | 3 | 3 | 3 |
| 4 | 4 | 4 | 4 |


In [19]:
col_vector = np.transpose(np.array([np.arange(1, 5)]))
np.repeat(col_vector, 4, axis=1)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

## Exercise 11
Generate a 4×4 matrix using [arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) and [tile](https://numpy.org/doc/stable/reference/generated/numpy.tile.html). Create a row vector for values 1 to 4 from an array generated by [arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) (check its shape, should be `(1, 4)`). Repeat that row vector four times to create a 4×4 matrix. Think and experiment with `reps` parameter of the [tile](https://numpy.org/doc/stable/reference/generated/numpy.tile.html) function. Your matrix should look like this:
| 1 | 2 | 3 | 4 |
|---|---|---|---|
| 1 | 2 | 3 | 4 |
| 1 | 2 | 3 | 4 |
| 1 | 2 | 3 | 4 |

In [20]:
np.tile(np.arange(1, 5), (4, 1))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

## Exercise 12
Write the code that creates an ordered matrix by row so each row goes from 1 till 4 but each column has a single number in it. Define matrix size via a constant. Write the code that shuffles just one row (put its index in `irow` variable). Change `irow` value to test that your code works.

In [36]:
irow = 2

# Your code goes here
grid = np.tile(np.arange(1, 5), (4, 1))

np.random.shuffle(grid[irow, :])
grid

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [2, 3, 1, 4],
       [1, 2, 3, 4]])

## Exercise 13
Write and test single row validation.

In [42]:
# matrix generated by row
grid = np.tile(np.arange(1, 10), (9, 1))

# row should be fine
print(np.unique(grid[1, :]).size == grid.shape[0])

# column not
print(np.unique(grid[:, 1]).size == grid.shape[0])

True
False


## Exercise 13
Write and test single block extraction code, block is defined by `i_block_row` and `i_block_col`.

In [45]:
i_block_row = 1
i_block_col = 0

Code for when grid is stacked by row.

In [ ]:

SUDOKU_SIZE = 9
BLOCK_SIZE = 3

# matrix generated by row
grid = np.tile(np.arange(1, SUDOKU_SIZE + 1), (SUDOKU_SIZE, 1))

grid[(i_block_row * BLOCK_SIZE):(i_block_row * BLOCK_SIZE + BLOCK_SIZE),
     (i_block_col * BLOCK_SIZE):(i_block_col * BLOCK_SIZE + BLOCK_SIZE)]

Code for when grid is stacked by column.

In [47]:

SUDOKU_SIZE = 9
BLOCK_SIZE = 3

# matrix generated by column
row_vector = np.array([np.arange(1, SUDOKU_SIZE + 1)])
col_vector = np.transpose(row_vector)
grid = np.repeat(col_vector, SUDOKU_SIZE, axis=1)


grid[(i_block_row * BLOCK_SIZE):(i_block_row * BLOCK_SIZE + BLOCK_SIZE),
     (i_block_col * BLOCK_SIZE):(i_block_col * BLOCK_SIZE + BLOCK_SIZE)]

array([[4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])