# Guess the animal

## Exercise 01
Test `input_yes_no` function here.

In [2]:
def input_yes_no(prompt):
    """Get [y]es/[n]o answer.

    Parameters
    ----------
    prompt : str


    Returns
    ----------
    logical
    """

    response = ""
    while response not in ["n", "y"]:
        response = input('Type "y" for yes and "n" for no. ' + prompt)

    return response == "y"

input_yes_no("Is this a pony?")    

False

## Exercise 02
Implement computation of the factorial via recursive computation. Write a function that implements the following formula in the main text.

In [3]:
def factorial(n):
    """Compute factorial.

    Parameters
    ----------
    n : int

    Returns
    ----------
    int
    """

    if n == 1:
        return 1
    else:
        return n * factorial(n - 1)

factorial(5)

120

## Exercise 03
Run cell below to define arrays.


In [6]:
oned_array = np.array([1, 2, 3, 4])
twod_array = np.array([[5, 6], [7, 8]])

Problem 01. Reshape `oned_array` into a 2D matrix using shape of the `twod_array` (do not hard code dimensions directly!)

In [7]:
np.reshape(oned_array, twod_array.shape)

array([[1, 2],
       [3, 4]])

Problem 02. Reshape `twod_array` into a 1Darray using shape of the `oned_array` (do not hard code dimensions directly!)

In [8]:
np.reshape(twod_array, oned_array.shape)

array([5, 6, 7, 8])

Problem 03. Reshape `twod_array` into a 1Darray using its own size (do not hard code dimensions directly!)

In [9]:
np.reshape(twod_array, (twod_array.size, ))

array([5, 6, 7, 8])

Problem 04. Reshape `twod_array` into a 1Darray via flatten.

In [10]:
twod_array.flatten()

array([5, 6, 7, 8])

## Exercise 04
Write code that generates a division-by-zero error but is handled via `try...except...`. In the `except` simply print out a message, so that you know that it handled the exception. Create another cell, copy the code and now check that the exception handling code is _not_ executed, if the error is not generated (i.e., divide by some non-zero number).

In [11]:
# Code when deivion-by-zero exception is raised
try:
    5 / 0
except:
    print("Something bad happened")

Something bad happened


In [12]:
# Code when deivion-by-zero exception is NOT raised
try:
    5 / 1
except:
    print("Something bad happened")

## Exercise 05
Implement handling for `KeyError` and `ZeroDivisionError`, they should print out different messages to check that it works. Test it by generating these runtime errors with your code.

Code that handles both exceptions but produces `ZeroDivisionError` exception

In [14]:

try:
    5 / 0
except KeyError:
    print("Nope, no such key")
except ZeroDivisionError:
    print("Please do not divide by zero!")

Please do not divide by zero!


Code that handles both exceptions but produces `KeyError` exception

In [15]:
try:
    {"a": 2}["b"]
except KeyError:
    print("Nope, no such key")
except ZeroDivisionError:
    print("Please do not divide by zero!")

Nope, no such key


## Exercise 06
Repeat exercise 05 but raise `KeyError` and `ZeroDivisionError` yourself.

In [16]:
try:
    raise KeyError
except KeyError:
    print("Nope, no such key")
except ZeroDivisionError:
    print("Please do not divide by zero!")

Nope, no such key


## Exercise 07
Implement the code with a simple an endless while loop in which you ask whether to continue or quit (decide on how you will handle the input). Once you finally opt to quit, raise `QuitTheGame` exception that should be handled by the `try except` code wrapped around the loop. Use code to handle `QuitTheGame` exception _specifically_ and print a message to show how said you are that the player is leaving.

In [17]:
class QuitTheGame(Exception):
    pass

# Your code goes here
try:
    while True:
        if input("Repeat again?").lower() == "no":
            raise QuitTheGame
except QuitTheGame:
    print("It is finally over!")

It is finally over!
